pagefaultgames/pokerogue-locales

- de/pokemon-summary.json
- en/pokemon-summary.json
https://github.com/pagefaultgames/pokerogue/pull/4490
> [Feature] Add new key for Friendship

- en/battler-tags.json
Added a key + the English line for the move Telekinesis
PR: https://github.com/pagefaultgames/pokerogue/pull/4506
Source for Lines
Bulbapedia : https://archives.bulbagarden.net/media/upload/1/11/Telekinesis_V.png
Please let me know if you have any questions.
> [Move][Translation] Telekinesis

- en/menu.json
Translation for [this PR](https://github.com/pagefaultgames/pokerogue/pull/3679)
> add locale english renameHelpEmoji

- .github/workflows/ci.yml
https://github.com/flx-sta/pokerogue-locales/actions/runs/11240148769
https://github.com/flx-sta/pokerogue-locales/actions/runs/11240158318
> add filename lint to not end with `messages.json`

- en/battler-tags.json
New locale keys for [Powder's implementation](https://github.com/pagefaultgames/pokerogue/pull/3662)
[Source for English text](https://www.youtube.com/watch?v=b0zEeH8jIHQ)
> [Move][EN] Powder

- en/battler-tags.json
New locale keys for https://github.com/pagefaultgames/pokerogue/pull/2658
> [Move][EN] Power Trick

- en/ability-trigger.json
Added Flash Fire key in ability-trigger
> Added Flash Fire key in ability-trigger

- en/ability-trigger.json
Part of this PR --> https://github.com/pagefaultgames/pokerogue/pull/4682
Source (from Smewkie) -->
> [Ability] Line for when a Pokemon with Mimicry returns to its original type

- en/mystery-encounters/fun-and-games-dialogue.json
- en/mystery-encounters/part-timer-dialogue.json
- en/mystery-encounters/shady-vitamin-dealer-dialogue.json
- en/mystery-encounters/training-session-dialogue.json
```json
{
"invalid_selection": "Pokémon must be healthy enough."
}
```
> Add `invalid_selection` key for  fun-and-games-dialogue.json

- en/move-trigger.json
Adds the text for Corrosive Gas' moveTrigger that I've implemented in the pokerogue repository.
[Source for English Text](https://youtu.be/Wk8GJTExyfE?t=1058)
[PokeRogue PR](https://github.com/pagefaultgames/pokerogue/pull/4793)
> [Move] [EN] Add Corrosive Gas text

- de/dialogue.json
> Fixed Brock Dialogue

- en/move-trigger.json
Companion PR: https://github.com/pagefaultgames/pokerogue/pull/4926
> Add Lunar Dance key

- de/battle.json
- es-ES/battle.json
- fr/battle.json
- it/battle.json
- ja/battle.json
- ko/battle.json
- pt-BR/battle.json
- zh-CN/battle.json
- zh-TW/battle.json
OG English PR:
https://github.com/pagefaultgames/pokerogue-locales/pull/56
> Translations for the number of eggs hatching to egg skip prompt

- de/menu.json
- en/menu.json
- es-ES/menu.json
- fr/menu.json
- it/menu.json
- ja/menu.json
- ko/menu.json
- pt-BR/menu.json
- zh-CN/menu.json
- zh-TW/menu.json
Tied to this PR:
https://github.com/pagefaultgames/pokerogue/pull/4973
> Add Login beta key

- en/menu.json
Localization key for this PR:
https://github.com/pagefaultgames/pokerogue/pull/4971
> Added Event Timer key

- en/splash-texts.json
Removes vgc_ref_1, agency_ref_1, pkmn_cry_1 splash messages pending further consideration
> Remove common splash text additions

- en/splash-texts.json
Reverts pagefaultgames/pokerogue-locales#81
> Revert "Add holiday splashes in English"

- en/move-trigger.json
Main PR: https://github.com/pagefaultgames/pokerogue/pull/5049
Source: https://bulbapedia.bulbagarden.net/wiki/Quash_(move)#In_other_games / https://abcboy101.github.io/poke-corpus/#q=postponed&s=xcosif3z0hQzcQ
> Add quash key

- en/modifier-type.json
Adds English entries for the Deep Sea Scale and Deep Sea Tooth items. Main PR here: https://github.com/pagefaultgames/pokerogue/pull/5078
> Add entries for Deep Sea Scale & Tooth

- en/settings.json
- en/starter-select-ui-handler.json
this change is connected to the PR to allow random selection of starters .
> Add randomization option to settings and starter select ui 

- en/move-trigger.json
I made https://github.com/pagefaultgames/pokerogue-locales/pull/89 which got merged a few days ago, just realized I fat fingered it and missed the comma. This fixes that
> Quash key fix

- th/game-stats-ui-handler.json
- zh-TW/trainer-titles.json
Removes extra comma in `th/game-stats-ui-handler.json` and adds missing comma in `zh-TW/trainer-titles.json`
> Fix broken json files

- en/filter-bar.json
Adding options to filter starters that have had exactly one or exactly two cost reductions.
> Adding two options to the cost reduction filter

- en/filter-bar.json
For PR-PR[#5161](https://github.com/pagefaultgames/pokerogue/pull/5161)
> Add sortByNumCaught and sortByNumHatched to starter select

- de/bgm-name.json
- en/bgm-name.json
- es-ES/bgm-name.json
- fr/bgm-name.json
- it/bgm-name.json
- ja/bgm-name.json
- ko/bgm-name.json
- pt-BR/bgm-name.json
- zh-CN/bgm-name.json
- zh-TW/bgm-name.json
Updates the Title BGM entry in all languages. Associated main repo PR here: https://github.com/pagefaultgames/pokerogue/pull/5189
> Update Title BGM entries

- en/dialogue.json
*The clerks had no dialogue, so I added quotes from Battle Subway Clerks from BW.
*worker and worker_female erroneously had the same dialogue. Added dialogue from USUM for worker.
> [Localisation] [Eng] Add worker, clerk and clerk_female dialogue to dialogue.json

- en/battle-scene.json
- fr/battle-scene.json
Localization PR related to this PR:
https://github.com/pagefaultgames/pokerogue/pull/5336
> Level up notification

- en/starter-select-ui-handler.json
Adding a new option to the starter select that lets you choose your tera type.
> Add tera button to starter select

- en/pokemon-form.json
This PR: https://github.com/pagefaultgames/pokerogue/pull/5386 makes use of the new flags in the code.
> Separate battle form names

- en/weather.json
> [Misc] Add defaultEffectMessage in weather

- en/modifier-type.json
Adds localization key and English name/description for "Mystical Rock" item implemented in pagefaultgames/pokerogue#4799.
> [Item][EN] Mystical Rock

- en/achv.json
Changed the names of the following achievements for
- Mega Evolving a Pokemon
- Gigantamaxing a Pokemon
- Flip Stat + Inverse Mode Completion
- Mono Fighting
- Mono Flying
- Mono Steel
- Mono Dark
> [Achievements] Update Achievement Names and fix english descriptions

- en/splash-texts.json
- fr/splash-texts.json
- pt-BR/splash-texts.json
> [Misc] Fix calls for {{pokemonName}}
