en/arena-tag.json, en/move-trigger.json
To coincide with the implementation of Water Pledge, Fire Pledge, and Grass Pledge in https://github.com/pagefaultgames/pokerogue/pull/4511. The added English keys have previously been approved by proofreaders.
=> [Move] Add translations for Pledge Moves

de/common.json, en/common.json, es/common.json, fr/common.json, it/common.json, ja/common.json
> [!TIP]
> https://github.com/pagefaultgames/pokerogue/pull/4550
derived from this code:
```ts
switch (lng) {
case "ja":
return `@[MONEY]{${numberFormattedString}}円`;
case "de":
case "es":
case "fr":
case "it":
return `@[MONEY]{${numberFormattedString} ₽}`;
default:
// English and other languages that use same format
return `@[MONEY]{₽${numberFormattedString}}`;
}
```
--------
=> [QoL] add `common:money` key

en/arena-flyout.json
I missed these keys when implementing their respective moves :despair:
Text is straightforward for the most part, being derived from the source move's name or, in the case of the Pledge combos, the effect descriptors from [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Fire_Pledge_(move)).
=> [EN] Arena flyout descriptors for Pledge combinations, Ion Deluge, and Lucky Chant

en/battle.json
New keys for default messages when an effect that's not a trapping ability or move prevents Pokemon from switching or fleeing.
First used in https://github.com/pagefaultgames/pokerogue/pull/4670
Source (for switching):
=> [Misc][EN] Default messages for disabled switch/run commands

en/modifier-type.json
> [!IMPORTANT]
> This updated description is based on balance changes to Multi-Lens in https://github.com/pagefaultgames/pokerogue/pull/4831. This PR should only be merged in after the balance changes have been approved by Devs and the Balance Team.
This changes a custom description for Multi-Lens to reflect planned changes to the item. The changes in detail are listed below:
- The maximum stack count for this item has been reduced from 3 to 2.
- The power reduction per hit has changed to a damage modifier such that
- 1x Multi-Lens changes from 40% * 2 _power_ -> 75% + 25% _damage_.
- 2x Multi-Lens changes from 25% * 3 _power_ -> 50% + 25% + 25% _damage_.
- The item now adheres to the same restrictions as [Parental Bond](https://bulbapedia.bulbagarden.net/wiki/Parental_Bond_(Ability)) …
=> [EN] Multi-Lens description update

en/splash-texts.json
"Make it Rain and your problems go away!" -> "Make It Rain and your problems go away!"
The move name has "It" capitalized.
=> Properly capitalize Make It Rain splash text

en/settings.json, fr/settings.json
Link to main repo PR: https://github.com/pagefaultgames/pokerogue/pull/4949
This PR adds a confirmation message in settings before disabling touch controls, like so:
The Yes/No is the generic Yes/No window used across the game, no need to do anything on that front
The text box can display 2 lines, with automatic wrap around so no need to bother about line breaks and there should be plenty of room.
For proofreaders, do you think something else should be added to make extra clear that if they don't have access to another mean to control the game they will get locked out if they say yes? That shouldn't be needed, right?
The second key "defaultConfirmMessage" is not used currently in the game, but if in the future a setting is added that does not need a specific confirmation message it will …
=> Add confirmation message for disabling touch controls in settings

en/battle.json, fr/battle.json
Goes with [PRPR#4913](https://github.com/pagefaultgames/pokerogue/pull/4913).
Implements the `eggsToHatch` argument passed to `eggSkipPrompt` in `battle.json`. This is intended to show the player how many eggs are about to hatch when prompted on whether to skip to egg summary, as seen below:
=> Add number of eggs hatching to egg skip prompt

en/splash-texts.json
Adds keys for `winter_1` through `winter_32` in the `xmas` category. English has 28 of these filled (subject to change), the rest are "Happy Holidays!" as a placeholder. Also adds splashes with more generic keys:
- common.vgc_ref_1
- common.agency_ref_1
- common.pkmn_cry_1
- halloween.halloween_1
- newYears.newyears_1
- newYears.newyears_2
=> Add holiday splashes in English

en/arena-flyout.json
The key that is suppsoed to display the move "Imprison" in arena-flyout was missing.
=>  Missing Imprison in arena-flyout.json

de/menu-ui-handler.json, de/menu.json, en/menu-ui-handler.json, en/menu.json, es-ES/menu-ui-handler.json, es-ES/menu.json, fr/menu-ui-handler.json, fr/menu.json, it/menu-ui-handler.json, it/menu.json, ja/menu-ui-handler.json, ja/menu.json, ko/menu-ui-handler.json, ko/menu.json, pt-BR/menu-ui-handler.json, pt-BR/menu.json, zh-CN/menu-ui-handler.json, zh-CN/menu.json, zh-TW/menu-ui-handler.json, zh-TW/menu.json
Moving the "Run History" option from the menu to the title menu, as per PR https://github.com/pagefaultgames/pokerogue/pull/5139.
No new text is required; existing text is moved from menu-ui-handler.json to menu.json.
=> Moving the "Run History" option

en/battler-tags.json
Magic Coat adds a battler tag which sends a message saying the "[Name] shrouded itself with Magic Coat!"
Related to #108, and needed for https://github.com/pagefaultgames/pokerogue/pull/5225.
The pokecorpus query for the move:
https://abcboy101.github.io/poke-corpus/#q=shrouded+itself&s=xcosif3z0hQzcQ
For convenience, here's the screenshots for the translations from Poke Corpus:
<details><summary>ja / en</summary>
</details>
<details><summary>fr</summary>
</details>
<details><summary>it</summary>
</details>
<details><summary>de / es-ES</summary>
</details>
<details><summary>ko / zh-CN / zh-TW</summary>
=> [Move] Add Magic Coat to battler-tags.json

en/move.json
Updates English Bouncy Bubble description to reflect changes planned in PR [#5269](https://github.com/pagefaultgames/pokerogue/pull/5269). It heals by 100% of the damage taken by the target rather than half. Other languages will need to be updated too.
=> Update Bouncy Bubble description for full HP drain

en/pokedex-ui-handler.json
https://github.com/pagefaultgames/pokerogue/pull/5282 introduces an option to show all form icons for a given species in the main page of the dex. This option comes with a button which needs a localized label.
=> Option to show forms in dex

en/party-ui-handler.json
This one had just slipped through. It has to be in this file due to how the logic in the party ui handler works. But it is a duplicate key so it can be just copied and pasted from other files.
=> Pokédex option in party menu

en/pokemon-form.json, en/pokemon-info.json
Adds keys related to [this](https://github.com/pagefaultgames/pokerogue/pull/5294) PR.
Adds the following keys:
- In `pokemon-info.json`:
- `eternal_floette_expanded`: Proper expanded name for Eternal Flower Floette
- `bloodmoon_ursaluna_expanded`: Proper expanded name for Bloodmoon Ursaluna
- `expandedNameALOLA`: Proper expanded name for Alolan forms. Passes `species` parameter, the species name. For example, "expandedNameALOLA" with "Ninetales" set as species would be "Alolan Ninetales" in English.
- `expandedNameGALAR`, `expandedNameHISUI`, `expandedNamePALDEA`: See above, for Galarian, Hisuian, and Paldean Forms.
- In `pokemon-form.json`:
- `floetteEternalFlower`: The form name for Eternal Flower Floette
- `ursalunaBloodmoon`: The form name for Bloodmoon Ursaluna
- …
=> Add keys for regional form names

en/pokemon-form.json, en/pokemon-info.json
[For this PR again](https://github.com/pagefaultgames/pokerogue/pull/5294) but with a better organized structure.
Essentially what I did was make 2 new sub-entries, arrays, whatever they're called, in `pokemon-form.json`: `regionalForm` and `appendForm`.
`regionalForm` has the names of the regional forms, similar to before, such as "Hisuian Form".
`appendForm` is for getting a mon's full name with its form attached.
For example, "Eternal Flower Floette", "Alolan Ninetales", "Dusk Mane Necrozma", "Hoopa Unbound", etc.
The sub-keys for `appendForm` are, right now, the first word in the Species enum name, before the underscore. So this would be ALOLA for Alolan forms, ETERNAL, BLOODMOON, etc. This _should_ hold up in the future. Right now there's a key for each of the regions with regional …
=> Organize form name/append form locales better

en/ability-trigger.json, en/arena-flyout.json, en/arena-tag.json
Adds a key for neutralizing gas removal and moves the neutralizing gas keys from ability-trigger to arena-tag (The key is still left in ability-trigger to avoid breaking anything, but should be removed once the main repo PR makes it to main). Also adds an arena-flyout key for neutralizing gas.
[Pokecorpus](https://abcboy101.github.io/poke-corpus/#q=neutralizing+gas&s=xcosif3z0hQzcQ)
=> Add keys for Neutralizing Gas, move NG keys to arena-tag.json

en/battler-tags.json
Adds the key for taunt removal - [Poke Corpus](https://abcboy101.github.io/poke-corpus/#q=shook+off+the+taunt&s=QccR7ok)
[Main PR](https://github.com/pagefaultgames/pokerogue/pull/5407)
=> Add taunt remove key

en/dialogue.json
This includes English dialogue entries for Hooligans, Musician, and Pilot. Male and female dialogue entries for Poké Fan, Rich, and Rich Kid are also added, but are currently generic text that should eventually be replaced with canon dialogue, but this is just to get them into a visually functional state.
https://github.com/pagefaultgames/pokerogue/pull/5520
<details><summary>Hooligans</summary>
</details>
<details><summary>Musician</summary>
</details>
<details><summary>Pilot</summary>
</details>
<details><summary>Poké Fan</summary>
</details>
<details><summary>Rich</summary>
</details>
<details><summary>Rich Kid</summary>
</details>
=> Add English dialogue for new trainer types

en/move-trigger.json
When this move grounds the target, the message created as fallDown should be displayed for the player.
Fix 5027 PR: (https://github.com/pagefaultgames/pokerogue/pull/5536)
Poke Corpus Fall Down message link: https://abcboy101.github.io/poke-corpus/#q=fell+straight+down!&s=e0ZuZVE
https://github.com/user-attachments/assets/3b12dcba-2f39-481e-a77b-61e11160a393
https://github.com/user-attachments/assets/2b6decc6-12f1-44f0-a4fd-f11acba99122
=> [Move][En] Added message for Smack Down and Thousand Arrows
